### ISSUE TITLE
InputStream input for `get-images-from-pdf`

### ISSUE THREAD

**Issue by todd-kim** [constacts/ragtacts#17]
If it's not a saved file, `ragtacts.loader.doc/get-images-from-pdf` requires a `InputStream` input.

https://github.com/constacts/ragtacts/blob/main/src/ragtacts/loader/doc.clj#L87

**Comment by dalzony** [comment]
https://github.com/constacts/ragtacts/commit/833d6a0d45f5e8d1ef98d8f5f95ae92564efbe5c
